name: Create a package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.1

    - name: Create Build Environment
      run: cmake -E make_directory build

    - name: Configure CMake
      run: |
        dir zlib
        cd build && cmake .. -DCMAKE_BUILD_TYPE=Release

    - name: Copy zconf.h
      run: copy build/zlib/zconf.h lib

    - name: Build
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cd build && cmake --build --parallel . --config Release

    - name: Copy files
      run: |
        mkdir package
        copy build\\Release\\*.dll package
        copy scripts\\* package
      
    - name: Package files
      run: powershell Compress-Archive -Path package\\* -DestinationPath MHDShellExtensions-${{github.ref_name}}.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        body: ${{ github.event.head_commit.message }}
        draft: false
        prerelease: false
        files: |
          MHDShellExtensions-${{github.ref_name}}.zip